name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
        # uses GitHub's checkout action to checkout code form the master branch
        - uses: actions/checkout@v2
        
        # sets up .NET Core SDK 3.1
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.0.305
            
          # publishes Blazor project to the release-folder
        - name: Publish .NET Core Project
          run: dotnet publish code.csproj -c Release -o release --nologo
          
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with: 
            personal_token: ${{ secrets.GITHUBPAGESTOKEN }}
            external_repository: matkv/code
            publish_dir: ./release/wwwroot
            user_name: matkv
            user_email: matkobusljeta@gmail.com
            publish_branch: master
